# src/orchestrator/agent_control.py
from typing import Dict, Any, List
import os
import json
import uuid
import time

from utils.logger import bind_trace
from agents.planner_agent import PlannerAgent
from agents.data_agent import DataAgent
from agents.insight_agent import InsightAgent
from agents.eval_agent import EvalAgent
from agents.creative_agent import CreativeAgent
from utils.schemas import Hypothesis

class AgentController:
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        is_testing = os.getenv("PYTEST_ACTIVE") == "1"

        enable = (
            False if is_testing else
            config.get("llm", {}).get("enable_llm", True)
        )

        # Initialize all agents with appropriate LLM config
        self.planner = PlannerAgent({
            **config.get("planner", {}),
            "enable_llm": enable,
            "llm": config.get("llm", {})
        })
        self.data_agent = DataAgent(config)
        self.insight_agent = InsightAgent({
            **config.get("insight", {}),
            "enable_llm": enable,
            "llm": config.get("llm", {})
        })
        self.eval_agent = EvalAgent()
        self.creative_agent = CreativeAgent({
            **config.get("creative", {}),
            "enable_llm": enable,
            "llm": config.get("llm", {})
        })

<<<<<<< HEAD

=======
    # -----------------------------------------------------
    # TRANSLATION HELPERS
    # -----------------------------------------------------
>>>>>>> 098e76f (Better logig system with input/output)
    def _translate_insights_to_hypotheses(
        self, raw_insights: List[Dict[str, Any]]
    ) -> List[Hypothesis]:

        out: List[Hypothesis] = []

        for i, it in enumerate(raw_insights or []):
            out.append({
                "id": it.get("id") or f"H{i+1}",
                "driver": it.get("driver") or it.get("metric") or "unknown",
                "description": it.get("hypothesis") or it.get("description") or "",
                "segment": it.get("segment") or it.get("segment_name") or "",
                "expected_signals": it.get("expected_signals") or it.get("signals") or []
            })
        return out

<<<<<<< HEAD

=======
    # -----------------------------------------------------
    # REPORT WRITER
    # -----------------------------------------------------
>>>>>>> 098e76f (Better logig system with input/output)
    def write_markdown_report(self, query: str, insights, creatives, trace_id, summary):
        report_dir = self.config["paths"].get("report_dir", "reports")
        os.makedirs(report_dir, exist_ok=True)

        md_path = os.path.join(report_dir, "report.md")

        with open(md_path, "w", encoding="utf-8") as f:
            f.write("# Ad Performance Diagnostic Report\n\n")
            f.write(f"**Trace ID:** `{trace_id}`\n\n")
            f.write(f"**Query:** {query}\n\n")

            f.write("## Dataset Summary\n")
            if isinstance(summary, dict):
                totals = summary.get("totals", {})
                f.write(f"- Date range: {summary.get('date_range')}\n")
                f.write(f"- Total spend: {totals.get('spend', 0)}\n")
                f.write(f"- Total revenue: {totals.get('revenue', 0)}\n")
                f.write(f"- Overall ROAS: {totals.get('overall_roas', 0)}\n\n")

            f.write("## Insights\n")
            if insights:
                for hyp in insights:
                    f.write(f"### {hyp['id']}\n")
                    f.write(f"- Driver: {hyp['driver']}\n")
                    f.write(f"- Description: {hyp['description']}\n")
                    f.write(f"- Segment: {hyp['segment']}\n")
                    f.write(f"- Confidence: {hyp.get('confidence')}\n")
                    f.write(f"- Evidence: {hyp.get('evidence')}\n\n")
            else:
                f.write("No insights available.\n")

            f.write("## Creative Recommendations\n")
            if creatives:
                for c in creatives:
                    rec = c.get("recommendation", {})
                    f.write(f"- Issue: {c.get('issue')}\n")
                    f.write(f"  - Headline: {rec.get('headline')}\n")
                    f.write(f"  - Primary text: {rec.get('primary_text')}\n")
                    f.write(f"  - CTA: {rec.get('cta')}\n\n")
            else:
                f.write("No creative recommendations.\n")

            f.write("\n---\nGenerated by AgentController\n")

        return md_path

    # -----------------------------------------------------
    # MAIN PIPELINE CONTROLLER (V2 LOGGING)
    # -----------------------------------------------------
    def run(self, query: str, trace_id: str = None) -> Dict[str, Any]:

        if trace_id is None:
            trace_id = str(uuid.uuid4())

        meta = {
            "trace_id": trace_id,
            "query": query,
            "start_ts": time.time()
        }

        report_dir = self.config["paths"]["report_dir"]
        os.makedirs(report_dir, exist_ok=True)

        with open(os.path.join(report_dir, "trace_meta.json"), "w") as f:
            json.dump(meta, f, indent=2)

        log = bind_trace(trace_id).bind(agent="run")

<<<<<<< HEAD
=======
        # -----------------------------
        # PIPELINE START
        # -----------------------------
>>>>>>> 098e76f (Better logig system with input/output)
        log.info({
            "event": "pipeline_start",
            "trace_id": trace_id,
            "query": query
        })

<<<<<<< HEAD

=======
        # -----------------------------
        # 1. PLANNER
        # -----------------------------
>>>>>>> 098e76f (Better logig system with input/output)
        t0 = time.time()
        plan = self.planner.plan(query, trace_id=trace_id)

        log.info({
            "event": "planner_complete",
            "trace_id": trace_id,
            "duration_sec": round(time.time() - t0, 3),
            "num_metrics": len(plan.get("metrics", [])),
            "num_segments": len(plan.get("segments", []))
        })

        with open(os.path.join(report_dir, "plan.json"), "w") as f:
            json.dump(plan, f, indent=2)

<<<<<<< HEAD
=======
        # -----------------------------
        # 2. DATA AGENT
        # -----------------------------
>>>>>>> 098e76f (Better logig system with input/output)
        t0 = time.time()
        data_bundle = self.data_agent.run(trace_id=trace_id)

        df = data_bundle["df"]
        summary = data_bundle["summary"]

        log.info({
            "event": "data_agent_complete",
            "trace_id": trace_id,
            "duration_sec": round(time.time() - t0, 3),
            "num_rows": len(df),
            "num_columns": len(df.columns)
        })

<<<<<<< HEAD

=======
        # -----------------------------
        # 3. INSIGHT AGENT
        # -----------------------------
>>>>>>> 098e76f (Better logig system with input/output)
        t0 = time.time()
        raw_insights = self.insight_agent.generate(query, summary, trace_id=trace_id)

        log.info({
            "event": "insight_agent_complete",
            "trace_id": trace_id,
            "duration_sec": round(time.time() - t0, 3),
            "num_raw_insights": len(raw_insights)
        })

<<<<<<< HEAD
=======
        # -----------------------------
        # 4. TRANSLATE TO HYPOTHESES
        # -----------------------------
>>>>>>> 098e76f (Better logig system with input/output)
        hypotheses = self._translate_insights_to_hypotheses(raw_insights)

        log.info({
            "event": "hypotheses_normalized",
            "trace_id": trace_id,
            "num_hypotheses": len(hypotheses)
        })

<<<<<<< HEAD
=======
        # -----------------------------
        # 5. EVALUATE HYPOTHESES
        # -----------------------------
>>>>>>> 098e76f (Better logig system with input/output)
        thresholds = self.config.get("thresholds", {})

        t0 = time.time()
        evaluated = self.eval_agent.evaluate(df, hypotheses, thresholds, trace_id=trace_id)

        log.info({
            "event": "evaluation_stage_complete",
            "trace_id": trace_id,
            "duration_sec": round(time.time() - t0, 3),
            "num_evaluated": len(evaluated)
        })

<<<<<<< HEAD

=======
        # -----------------------------
        # 6. CREATIVE AGENT
        # -----------------------------
>>>>>>> 098e76f (Better logig system with input/output)
        t0 = time.time()
        creatives = self.creative_agent.generate(df, trace_id=trace_id)

        log.info({
            "event": "creative_agent_complete",
            "trace_id": trace_id,
            "duration_sec": round(time.time() - t0, 3),
            "num_creatives": len(creatives)
        })

<<<<<<< HEAD
=======
        # -----------------------------
        # SAVE RESULTS
        # -----------------------------
>>>>>>> 098e76f (Better logig system with input/output)
        with open(os.path.join(report_dir, "insights.json"), "w") as f:
            json.dump(evaluated, f, indent=2)

        with open(os.path.join(report_dir, "creatives.json"), "w") as f:
            json.dump(creatives, f, indent=2)

        # Report
        self.write_markdown_report(query, evaluated, creatives, trace_id, summary)

<<<<<<< HEAD
=======
        # -----------------------------
        # PIPELINE END
        # -----------------------------
>>>>>>> 098e76f (Better logig system with input/output)
        log.info({
            "event": "pipeline_end",
            "trace_id": trace_id,
            "total_insights": len(evaluated),
            "total_creatives": len(creatives),
            "duration_sec": round(time.time() - meta["start_ts"], 3)
        })

        return {
            "insights": evaluated,
            "creatives": creatives,
            "trace_id": trace_id
        }
